### ISSUE TITLE
Create CBOR examples

### ISSUE THREAD

**Issue by erdtman** [cwt-cnf/i-d#1]
Examples should be verifiable CWTs and potentially collected in an appendix too.

**Comment by selfissued** [comment]
Agreed

**Comment by LudwigSeitz** [comment]
Do you mean "verifiable" as in parseable, or do you want the examples to include encryption/signatures/macs?

**Comment by erdtman** [comment]
I would like the examples to be as complete as possible, i.e. verifiable
with keys etc. If that becomes bloated in the main text I think it would be
good with an appendix.

//Samuel

**Comment by selfissued** [comment]
I'm fine with adding CBOR diagnostic examples for this round, as @LudwigSeitz has created with PR #3 .  If we later want full COSE objects corresponding to the examples, I agree that those should go into an appendix.  Note, however that RFC 7800 shipped without such an appendix, so I don't think it's mandatory.

**Comment by erdtman** [comment]
Looks good to me I had just two minor comments.

**Comment by LudwigSeitz** [comment]
Seems like we closed this.
