### ISSUE TITLE
AD review: Use Encrypted_COSE_Key instead of COSE_Encrypt0 in 3.3

### ISSUE THREAD

**Issue by LudwigSeitz** [cwt-cnf/i-d#20]
Discussion from Ben's review: 

>>     The following example CWT Claims Set of a CWT (using CBOR diagnostic
>>     notation, with linebreaks for readability) illustrates the use of an
>>     encrypted symmetric key as the "Encrypted_COSE_Key" member value:
>>
>>    {
>>     /iss/ 1 : "coaps://server.example.com",
>>     /sub/ 2 : "24400320",
>>     /aud/ 3: "s6BhdRkqt3",
>>     /exp/ 4 : 1311281970,
>>     /iat/ 5 : 1311280970,
>>     /cnf/ 8 : {
>>     /COSE_Encrypt0/ 2 : [
>>
>> Should this be "/Encrypted_COSE_Key/" and not "/COSE_Enrypt0/"?
>>
>> [I did not validate the COSE_Encrypt0 output]
>>
>
> COSE_Encrypt0 is a defined construct of COSE, while Encrypted_COSE_Key 
> is not. We'd have to define it or write an explanatory comment.

Maybe I'm confused about how the diagnostic notation works, but the
top-level CWT map key name ("claim") is "Encrypted_COSE_Key", as matches
iss/sub/aud/etc. in the preceding notation.  If the rules are different for
map keys whose corresponding values are themselves structured data types,
then I should just unconfuse myself and we can move on with things...

**Comment by LudwigSeitz** [comment]
Ben is right, we need to replace COSE_Encrypt0 with Encrypted_COSE_Key. 

I missed out that we had defined the latter somehow.

**Comment by hannestschofenig** [comment]
OK. Fine for me.
