### ISSUE TITLE
AD review: Section 6 clarify how credentials verify confidentiality of CWT

### ISSUE THREAD

**Issue by LudwigSeitz** [cwt-cnf/i-d#23]
From the review and discussion:

>> Section 6
>>
>>     ensure correct processing.  The recipient needs to be able to use
>>     credentials to verify the authenticity, integrity, and potentially
>>     the confidentiality of the CWT and its content.  This requires the
>>
>> Just from a rhetorical point of view, can you help me understand how
>> credentials would be used to verify the confidentiality of a CWT?  It
>> seems like this depends on either (or both of) how the CWT is
>> transmitted or how it is prepared, and I am not sure how the recipient's
>> credentials come into play.
>>
>
> This text is referring to the issuer's credentials (e.g. the 
> Authorization Server issuing the CWT), that the recipient needs to 
> verify the CWT. Do you want us to clarify this sentence?

Note that I was specifically asking about "potentially the
confidentiality"; I don't understand the intended workflow for verification
of confidentiality (and thus which credentials are involved).  I don't
really see how a credential held solely by the issuer could proide
confidentiality protection when it needs to be understood by some other
protocol participant.

**Comment by LudwigSeitz** [comment]
Old: "The recipient needs to be able to use credentials to verify the authenticity, integrity, and potentially the confidentiality of the CWT and its content."

Suggested new: "The recipient needs to be able to use credentials to verify the authenticity and integrity of the CWT.  Furthermore the recipient may need to be able to decrypt either the whole CWT or encrypted parts thereof (see section 3.3)."

**Comment by erdtman** [comment]
Works for me!

**Comment by hannestschofenig** [comment]
Works also for me. Thanks for the new text.
