### ISSUE TITLE
Use RFC 2119 capitalizations

### ISSUE THREAD

**Issue by erdtman** [cwt-cnf/i-d#8]
(SHOULD) "Applications utilizing proof of possession *should* also utilize audience restriction, as described in Section 4.1.3 of [JWT], as it provides different protections."

(MUST) "Applications that require the proof-of-possession keys communicated with it to be understood and processed *must* ensure that the parts of this specification that they use are implemented."

**Comment by erdtman** [comment]
Review comment from Roman

**Comment by selfissued** [comment]
Please make this change.
