### ISSUE TITLE
Rephrasing needed for audience text 

### ISSUE THREAD

**Issue by erdtman** [cwt-cnf/i-d#9]
Review comment from Roman
(12) (Editorial) Page 8, Section 4, Per

   Applications utilizing proof of possession should also utilize
   audience restriction, as described in Section 4.1.3 of [JWT], as it
   provides different protections.  Proof of possession can be used by
   recipients to reject messages from unauthorized senders.  Audience
   restriction can be used by recipients to reject messages intended for
   different recipients.

The flow of this sentence is off for me.  Sentence #1 asserts the need for audience restrictions.  Sentence #3 describes the benefit of Sentence #1.  Sentence #2 interjects with something that seems unrelated to this need-benefit pairing.

**Comment by LudwigSeitz** [comment]
I think this has been fixed in a prior update.
